{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Main Difference between using dockerfile and docker-compose"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## dockerfile\n",
    "\n",
    "This is like a single recipe for you to create an image that you want. For example, a nice laksa dish or kueh lapis.\n",
    "\n",
    "The benefit of this is to be able to create a single docker image for you to run for your container."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## dockercompose\n",
    "\n",
    "This is like several of those dishes being put together to coordinate and form a meal, laksa as a main course and kueh lapis for desserts.\n",
    "\n",
    "docker-compose is for you to run multiple containers easily."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
